yolo_model:

  config_file:
    name: yolov3_final.cfg
  weight_file:
    name: yolov3_2000.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - traffic_L
      - traffic_R
      - traffic_G
      - v_30
      - v_50
